name: Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update
        run: make update
      - name: Add, Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: update knowledge base"
          commit_user_email: ivan.gabriele@protonmail.com
          commit_user_name: Ivan Gabriele
      - name: Create Release Tag
        id: tag
        run: echo "RELEASE_TAG=v$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.tar.gz"
          token: ${{ secrets.GH_PAT }}
          tag: ${{ steps.tag.outputs.RELEASE_TAG }}
