name: Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update
        run: make update
      - name: Create Release Tag
        id: tag
        run: echo "RELEASE_TAG=v$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz"
          tag: ${{ steps.tag.outputs.RELEASE_TAG }}
