name: Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update
        run: make update
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          git_config_global: true
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          trust_level: ultimate
      - name: Add, Commit & Push
        run: |
          git config --global user.email "ivan.gabriele+github@protonmail.com"
          git config --global user.name "Ivan Gabriele (Github)"
          git add .
          git commit -m "feat: update knowledge base"
          git push
      - name: Create Release Tag
        id: tag
        run: echo "RELEASE_TAG=v$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.tar.gz"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.tag.outputs.RELEASE_TAG }}
