name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Knowledge Base
        run: make update

      - name: Commit and push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: update knowledge base"
          commit_user_email: ivan.gabriele@protonmail.com
          commit_user_name: Ivan Gabriele
